/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drawing.app;

import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author hussein
 */
public class DrawingPanel extends javax.swing.JPanel {

    Graphics2D g2D;
    ArrayList<Rectangle> rectangles = new ArrayList<>();
    int oldX, oldY, newX, newY;

    /**
     * Creates new form NewJPanel
     */
    public DrawingPanel() {
        Icon icon = new ImageIcon("/home/hussein/Downloads/thin-rectangle.png");
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g2D = (Graphics2D) g;

        for (Rectangle rec : rectangles) {
            g2D.draw(rec);
//            g2D.drawRect(rec.getX(), rec.getY(), (int) rec.getWidth(), (int) rec.getHeight());
        }
//        g2D.drawRect(100, 100, 100, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        button2 = new javax.swing.JToggleButton();
        button1 = new javax.swing.JToggleButton();

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DrawingPanel.this.mouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DrawingPanel.this.mousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DrawingPanel.this.mouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("(null, null)");

        button2.setText("Square");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button1.setText("Rectangle");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(button1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button1)
                        .addComponent(button2))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mousePressed

//        System.out.println(newRectangle);
        if (button1.isSelected()) {
            jLabel1.setText("Mouse Pressed: " + evt.getPoint().toString());
            this.oldX = evt.getX();
            this.oldY = evt.getY();
            Rectangle rec = new Rectangle(evt.getX(), evt.getY(), 0, 0);
            rectangles.add(rec);
            this.repaint();
        }
        if (button2.isSelected()) {
            jLabel1.setText("Mouse Pressed: " + evt.getPoint().toString());
            this.oldX = evt.getX();
            this.oldY = evt.getY();
            Rectangle rec = new Rectangle(evt.getX(), evt.getY(), 0, 0);
            rectangles.add(rec);
            this.repaint();
        }
    }//GEN-LAST:event_mousePressed

    private void mouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseReleased
//        jLabel1.setText("Mouse Rekeased: " + evt.getPoint().toString());
//        System.out.println(newRectangle);

        button1.setSelected(false);
        button2.setSelected(false);
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_mouseReleased

    private void mouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseDragged
//        jLabel1.setText("Mouse Dragged: " + evt.getPoint().toString());
//        System.out.println(newRectangle);
        if (button1.isSelected()) {
            this.newX = evt.getX();
            this.newY = evt.getY();
            rectangles.get(rectangles.size() - 1).width = this.newX - this.oldX;
            rectangles.get(rectangles.size() - 1).height = this.newY - this.oldY;
            this.repaint();
        }
        if (button2.isSelected()) {
            this.newX = evt.getX();
            this.newY = evt.getY();
            rectangles.get(rectangles.size() - 1).width = this.newX - this.oldX;
            rectangles.get(rectangles.size() - 1).height = this.newX - this.oldX;
            this.repaint();
        }
    }//GEN-LAST:event_mouseDragged

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.CROSSHAIR_CURSOR));
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.CROSSHAIR_CURSOR));
    }//GEN-LAST:event_button1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton button1;
    private javax.swing.JToggleButton button2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
